In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('/content/drive/My Drive/datab.csv')

In [ ]:
df.head()

,Patient_ID,Age,Family_History,BMI,High_Fat_Diet,Smoking,Alcohol,HRT_Usage,Late_Menopause,No_or_Late_Pregnancy,Breastfed,Estrogen_Cosmetics,Risk_Level
0,P_0514,82,No,35.7,Yes,No,No,Yes,No,No,Yes,Yes,High
1,P_1635,82,No,27.5,Yes,No,No,No,No,No,Yes,Yes,Moderate
2,P_3447,82,Yes,31.7,Yes,No,Yes,No,No,Yes,Yes,No,High
3,P_3736,82,Yes,31.5,Yes,No,No,No,No,Yes,No,Yes,High
4,P_2462,82,No,35.1,Yes,No,No,No,No,Yes,No,Yes,High

In [ ]:
df

,Patient_ID,Age,Family_History,BMI,High_Fat_Diet,Smoking,Alcohol,HRT_Usage,Late_Menopause,No_or_Late_Pregnancy,Breastfed,Estrogen_Cosmetics,Risk_Level
0,P_0514,82,No,35.7,Yes,No,No,Yes,No,No,Yes,Yes,High
1,P_1635,82,No,27.5,Yes,No,No,No,No,No,Yes,Yes,Moderate
2,P_3447,82,Yes,31.7,Yes,No,Yes,No,No,Yes,Yes,No,High
3,P_3736,82,Yes,31.5,Yes,No,No,No,No,Yes,No,Yes,High
4,P_2462,82,No,35.1,Yes,No,No,No,No,Yes,No,Yes,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4488,P_SYN_1433,82,No,29.8,No,No,No,No,No,No,Yes,No,Low
4489,P_1598,82,No,33.7,Yes,No,No,Yes,No,No,No,No,High
4490,P_SYN_0099,82,No,22.5,Yes,No,No,No,No,No,Yes,No,Low
4491,P_SYN_0779,82,No,30.5,No,No,No,No,No,No,No,No,Low
4492,P_2881,82,No,35.3,Yes,Yes,No,No,Yes,Yes,No,No,High

In [ ]:
df = df.drop(columns='Patient_ID',axis=1)
df.head()
df = df.drop(columns='Age',axis=1)
df.head()

,Family_History,BMI,High_Fat_Diet,Smoking,Alcohol,HRT_Usage,Late_Menopause,No_or_Late_Pregnancy,Breastfed,Estrogen_Cosmetics,Risk_Level
0,No,35.7,Yes,No,No,Yes,No,No,Yes,Yes,High
1,No,27.5,Yes,No,No,No,No,No,Yes,Yes,Moderate
2,Yes,31.7,Yes,No,Yes,No,No,Yes,Yes,No,High
3,Yes,31.5,Yes,No,No,No,No,Yes,No,Yes,High
4,No,35.1,Yes,No,No,No,No,Yes,No,Yes,High

In [ ]:
df.head()

,Family_History,BMI,High_Fat_Diet,Smoking,Alcohol,HRT_Usage,Late_Menopause,No_or_Late_Pregnancy,Breastfed,Estrogen_Cosmetics,Risk_Level
0,No,35.7,Yes,No,No,Yes,No,No,Yes,Yes,High
1,No,27.5,Yes,No,No,No,No,No,Yes,Yes,Moderate
2,Yes,31.7,Yes,No,Yes,No,No,Yes,Yes,No,High
3,Yes,31.5,Yes,No,No,No,No,Yes,No,Yes,High
4,No,35.1,Yes,No,No,No,No,Yes,No,Yes,High

In [ ]:
df['Risk_Level']=df['Risk_Level'].map({'High':2,'Moderate':1,'Low':0})
df['Family_History'] = df['Family_History'].map({'No': 0, 'Yes': 1})
df['High_Fat_Diet'] = df['High_Fat_Diet'].map({'No': 0, 'Yes': 1})
df['Smoking'] = df['Smoking'].map({'No': 0, 'Yes': 1})
df['Alcohol'] = df['Alcohol'].map({'No': 0, 'Yes': 1})
df['HRT_Usage'] = df['HRT_Usage'].map({'No': 0, 'Yes': 1})
df['Late_Menopause'] = df['Late_Menopause'].map({'No': 0, 'Yes': 1})
df['No_or_Late_Pregnancy'] = df['No_or_Late_Pregnancy'].map({'No': 0, 'Yes': 1})
df['Breastfed'] = df['Breastfed'].map({'No': 0, 'Yes': 1})
df['Estrogen_Cosmetics'] = df['Estrogen_Cosmetics'].map({'No': 0, 'Yes': 1})

In [ ]:
df.head()

,Family_History,BMI,High_Fat_Diet,Smoking,Alcohol,HRT_Usage,Late_Menopause,No_or_Late_Pregnancy,Breastfed,Estrogen_Cosmetics,Risk_Level
0,0,35.7,1,0,0,1,0,0,1,1,2
1,0,27.5,1,0,0,0,0,0,1,1,1
2,1,31.7,1,0,1,0,0,1,1,0,2
3,1,31.5,1,0,0,0,0,1,0,1,2
4,0,35.1,1,0,0,0,0,1,0,1,2

In [ ]:
corr = df.corr()
corr

,Family_History,BMI,High_Fat_Diet,Smoking,Alcohol,HRT_Usage,Late_Menopause,No_or_Late_Pregnancy,Breastfed,Estrogen_Cosmetics,Risk_Level
Family_History,1.000000,0.122611,0.090231,0.052957,0.062048,0.065804,0.083998,0.096165,-0.083722,0.043702,0.470312
BMI,0.122611,1.000000,0.180527,0.083782,0.102532,0.143783,0.126675,0.125527,-0.125046,0.104717,0.506949
High_Fat_Diet,0.090231,0.180527,1.000000,0.069366,0.074664,0.097878,0.059131,0.090797,-0.086572,0.052368,0.373863
Smoking,0.052957,0.083782,0.069366,1.000000,0.048958,0.064695,0.062963,0.062273,-0.090417,0.062898,0.272029
Alcohol,0.062048,0.102532,0.074664,0.048958,1.000000,0.104976,0.087193,0.077169,-0.084263,0.086467,0.351428
HRT_Usage,0.065804,0.143783,0.097878,0.064695,0.104976,1.000000,0.075544,0.123141,-0.125148,0.113693,0.469941
Late_Menopause,0.083998,0.126675,0.059131,0.062963,0.087193,0.075544,1.000000,0.088988,-0.086794,0.056831,0.318505
No_or_Late_Pregnancy,0.096165,0.125527,0.090797,0.062273,0.077169,0.123141,0.088988,1.000000,-0.089649,0.067044,0.351458
Breastfed,-0.083722,-0.125046,-0.086572,-0.090417,-0.084263,-0.125148,-0.086794,-0.089649,1.000000,-0.102353,-0.381331
Estrogen_Cosmetics,0.043702,0.104717,0.052368,0.062898,0.086467,0.113693,0.056831,0.067044,-0.102353,1.000000,0.326177
Risk_Level,0.470312,0.506949,0.373863,0.272029,0.351428,0.469941,0.318505,0.351458,-0.381331,0.326177,1.000000

In [ ]:
prediction_vars = ['Family_History', 'High_Fat_Diet', 'Smoking', 'Alcohol', 'HRT_Usage', 'Late_Menopause', 'No_or_Late_Pregnancy', 'Breastfed', 'Estrogen_Cosmetics']

In [ ]:
from sklearn.model_selection import train_test_split
train,test = train_test_split(df,test_size=0.15,random_state=1)

In [ ]:
train_x = train[prediction_vars]
train_y = train['Risk_Level']
test_x = test[prediction_vars]
test_y = test['Risk_Level']

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
train_x = scaler.fit_transform(train_x)
test_x = scaler.transform(test_x)

In [ ]:
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

In [ ]:
model = MLPClassifier(hidden_layer_sizes=(100,100,100),max_iter=500)

In [ ]:
model.fit(train_x,train_y)

MLPClassifier(hidden_layer_sizes=(100, 100, 100), max_iter=500)

In [ ]:
predicted = model.predict(test_x)

In [ ]:
predicted = model.predict(test_x)

from sklearn.metrics import (
    confusion_matrix, precision_score, recall_score,
    accuracy_score, f1_score, classification_report
)

print("Confusion Matrix:")
print(confusion_matrix(test_y, predicted))

print("\nMetrics:")
print(f"Accuracy : {accuracy_score(test_y, predicted):.2f}")
print(f"Precision: {precision_score(test_y, predicted, average='weighted', zero_division=0):.2f}")
print(f"Recall   : {recall_score(test_y, predicted, average='weighted', zero_division=0):.2f}")
print(f"F1 Score : {f1_score(test_y, predicted, average='weighted', zero_division=0):.2f}")

print("\nClassification Report:")
print(classification_report(test_y, predicted, zero_division=0))

Confusion Matrix:
[[224   0   0]
 [ 19 144  60]
 [  0   8 219]]

Metrics:
Accuracy : 0.87
Precision: 0.88
Recall   : 0.87
F1 Score : 0.86

Classification Report:
              precision    recall  f1-score   support

           0       0.92      1.00      0.96       224
           1       0.95      0.65      0.77       223
           2       0.78      0.96      0.87       227

    accuracy                           0.87       674
   macro avg       0.88      0.87      0.86       674
weighted avg       0.88      0.87      0.86       674

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
import joblib

pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("model", RandomForestClassifier(
        n_estimators=300,
        class_weight="balanced",
        random_state=42
    ))
])

pipeline.fit(train_x, train_y)

joblib.dump(pipeline, "breast_risk_model.joblib")

['breast_risk_model.joblib']